[package]
name = "atcoder"
version = "0.1.0"
authors = ["htlsne <htlsne23@gmail.com>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
